credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: "hashed_password_1"  # Substitua por senha hash
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: "hashed_password_2"  # Substitua por senha hash
cookie:
  expiry_days: 30
  key: random_signature_key  # Deve ser uma string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
